import { useEffect, useMemo, useState } from 'react'
import { Columns3, List, Pencil, Plus, Search, Trash2, UserRound, X } from 'lucide-react'
import Sidebar from '../components/Sidebar'
import { listarClientes } from '../api/clientesService'
import { criarContato, excluirContato, listarContatos, obterConfiguracoesCrm, salvarContato } from '../api/automationService'
import { escolherClienteInicial } from '../utils/clienteAtivo'

const vazio = (clienteId = '', etapa = '') => ({ cliente_id: clienteId, canal: 'manual', nome: '', sobrenome: '', telefone: '', email: '', instagram_usuario: '', facebook_usuario: '', etapa_id: etapa, qualidade_id: '', tags: [], respostas: [] })
function Contatos() {
  const [clientes, setClientes] = useState([]), [clienteId, setClienteId] = useState(''), [contatos, setContatos] = useState([])
  const [config, setConfig] = useState({ etapas: [], tags: [], qualidades: [] }), [modo, setModo] = useState('kanban'), [busca, setBusca] = useState('')
  const [editando, setEditando] = useState(null), [mensagem, setMensagem] = useState('')
  useEffect(() => { listarClientes().then((x) => { setClientes(x); setClienteId(escolherClienteInicial(x)) }).catch((e) => setMensagem(e.message)) }, [])
  async function carregar(id = clienteId) { if (!id) return; try { const [c, cfg] = await Promise.all([listarContatos(id), obterConfiguracoesCrm(id)]); setContatos(c); setConfig(cfg) } catch (e) { setMensagem(e.message) } }
  useEffect(() => { carregar(clienteId) }, [clienteId])
  const filtrados = useMemo(() => contatos.filter((c) => `${c.nome} ${c.sobrenome} ${c.email || ''} ${c.telefone || ''}`.toLowerCase().includes(busca.toLowerCase())), [contatos, busca])
  const opcao = (lista, id) => lista.find((x) => x.id === id)
  async function salvar(e) { e.preventDefault(); try { editando.id ? await salvarContato(editando.id, editando) : await criarContato(editando); setEditando(null); await carregar(); setMensagem('Lead salvo.') } catch (erro) { setMensagem(erro.message) } }
  async function mover(contato, etapaId) { await salvarContato(contato.id, { ...contato, cliente_id: clienteId, etapa_id: etapaId }); await carregar() }
  async function remover(id) { if (!confirm('Excluir este lead?')) return; await excluirContato(id); await carregar() }
  const Cartao = ({ contato }) => { const qualidade = opcao(config.qualidades, contato.qualidade_id); return <article className="lead-card" draggable onDragStart={(e) => e.dataTransfer.setData('lead-id', contato.id)}><header><UserRound size={18}/><strong>{contato.nome} {contato.sobrenome}</strong></header>{qualidade && <span className="crm-chip" style={{background: qualidade.cor_fundo, color: qualidade.cor_texto}}>{qualidade.nome}</span>}<small>{contato.email || contato.instagram_usuario || contato.telefone || 'Sem contato informado'}</small><div className="lead-tags">{(contato.tags || []).map((id) => { const tag = opcao(config.tags, id); return tag && <span key={id} style={{background:tag.cor_fundo,color:tag.cor_texto}}>{tag.nome}</span> })}</div><footer><button onClick={() => setEditando({...contato, cliente_id: clienteId})}><Pencil size={14}/></button><button onClick={() => remover(contato.id)}><Trash2 size={14}/></button></footer></article> }
  return <div className="layout-app"><Sidebar/><main className="conteudo-principal pagina-crm"><header className="topo-pagina"><div><h1>CRM</h1><p>Leads, conversas e andamento comercial separados por cliente.</p></div><button className="botao-primario" onClick={() => setEditando(vazio(clienteId, config.etapas[0]?.id))}><Plus size={16}/> Novo lead</button></header>{mensagem && <p className="mensagem-integracao">{mensagem}</p>}
    <section className="crm-toolbar"><label>Cliente<select value={clienteId} onChange={(e) => setClienteId(e.target.value)}>{clientes.map((x)=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><div className="crm-busca"><Search size={16}/><input placeholder="Buscar lead" value={busca} onChange={(e)=>setBusca(e.target.value)}/></div><div className="crm-modos"><button className={modo==='lista'?'ativo':''} onClick={()=>setModo('lista')}><List size={16}/> Lista</button><button className={modo==='kanban'?'ativo':''} onClick={()=>setModo('kanban')}><Columns3 size={16}/> Kanban</button></div></section>
    {modo === 'kanban' ? <section className="crm-kanban">{config.etapas.map((etapa)=><div className="kanban-coluna" key={etapa.id} onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{const id=e.dataTransfer.getData('lead-id'); const c=contatos.find(x=>x.id===id); if(c)mover(c,etapa.id)}}><header style={{background:etapa.cor_fundo,color:etapa.cor_texto}}><strong>{etapa.nome}</strong><span>{filtrados.filter(c=>c.etapa_id===etapa.id).length}</span></header><div>{filtrados.filter(c=>(c.etapa_id || config.etapas[0]?.id)===etapa.id).map(c=><Cartao key={c.id} contato={c}/>)}</div></div>)}</section> : <section className="crm-lista"><table><thead><tr><th>Lead</th><th>Contato</th><th>Redes sociais</th><th>Etapa</th><th>Qualidade</th><th></th></tr></thead><tbody>{filtrados.map(c=><tr key={c.id}><td><strong>{c.nome} {c.sobrenome}</strong></td><td>{c.email}<small>{c.telefone}</small></td><td>{c.instagram_usuario && `IG: ${c.instagram_usuario}`}<small>{c.facebook_usuario && `FB: ${c.facebook_usuario}`}</small></td><td>{opcao(config.etapas,c.etapa_id)?.nome || 'Sem etapa'}</td><td>{opcao(config.qualidades,c.qualidade_id)?.nome || 'Não informada'}</td><td><button onClick={()=>setEditando({...c,cliente_id:clienteId})}><Pencil size={15}/></button><button onClick={()=>remover(c.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></section>}
    {editando && <div className="crm-modal-fundo"><form className="crm-modal" onSubmit={salvar}><header><h2>{editando.id?'Editar lead':'Novo lead'}</h2><button type="button" onClick={()=>setEditando(null)}><X/></button></header><div className="crm-form-grid"><label>Nome<input required value={editando.nome} onChange={e=>setEditando({...editando,nome:e.target.value})}/></label><label>Sobrenome<input value={editando.sobrenome} onChange={e=>setEditando({...editando,sobrenome:e.target.value})}/></label><label>Telefone<input value={editando.telefone || ''} onChange={e=>setEditando({...editando,telefone:e.target.value})}/></label><label>E-mail<input type="email" value={editando.email || ''} onChange={e=>setEditando({...editando,email:e.target.value})}/></label><label>Usuário Instagram<input value={editando.instagram_usuario || ''} onChange={e=>setEditando({...editando,instagram_usuario:e.target.value})}/></label><label>Usuário Facebook<input value={editando.facebook_usuario || ''} onChange={e=>setEditando({...editando,facebook_usuario:e.target.value})}/></label><label>Etapa<select value={editando.etapa_id || ''} onChange={e=>setEditando({...editando,etapa_id:e.target.value})}>{config.etapas.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label>Qualidade<select value={editando.qualidade_id || ''} onChange={e=>setEditando({...editando,qualidade_id:e.target.value})}><option value="">Não informada</option>{config.qualidades.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label></div><fieldset><legend>Tags</legend>{config.tags.map(x=><label className="opcao-checkbox" key={x.id}><input type="checkbox" checked={(editando.tags||[]).includes(x.id)} onChange={e=>setEditando({...editando,tags:e.target.checked?[...(editando.tags||[]),x.id]:(editando.tags||[]).filter(id=>id!==x.id)})}/>{x.nome}</label>)}</fieldset><section className="crm-log"><h3>Histórico da conversa</h3>{(editando.respostas||[]).length===0?<small>Nenhuma interação registrada.</small>:(editando.respostas||[]).map((x,i)=><div key={i}><strong>{x.pergunta || x.identificador || 'Interação'}</strong><p>{String(x.resposta ?? '')}</p></div>)}</section><button className="botao-primario" type="submit">Salvar lead</button></form></div>}
  </main></div>
}
export default Contatos
