services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
      args:
        VITE_AUTH_SERVICE_URL: ${VITE_AUTH_SERVICE_URL}
        VITE_CONTENT_SERVICE_URL: ${VITE_CONTENT_SERVICE_URL}
        VITE_SOCIAL_SERVICE_URL: ${VITE_SOCIAL_SERVICE_URL}

    container_name: social-media-frontend

    restart: unless-stopped

    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"

    environment:
      FRONTEND_CONTAINER_PORT: ${FRONTEND_CONTAINER_PORT}
      NGINX_ENVSUBST_FILTER: ${NGINX_ENVSUBST_FILTER}

    networks:
      - plataforma_network

networks:
  plataforma_network:
    external: true
