FROM node:20-alpine AS build

WORKDIR /code

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_AUTH_SERVICE_URL
ARG VITE_CONTENT_SERVICE_URL
ARG VITE_SOCIAL_SERVICE_URL
ENV VITE_AUTH_SERVICE_URL=${VITE_AUTH_SERVICE_URL}
ENV VITE_CONTENT_SERVICE_URL=${VITE_CONTENT_SERVICE_URL}
ENV VITE_SOCIAL_SERVICE_URL=${VITE_SOCIAL_SERVICE_URL}

RUN npm run build


FROM nginx:alpine

COPY nginx.conf.template /etc/nginx/templates/default.conf.template
COPY --from=build /code/dist /usr/share/nginx/html
