services:
  auth-service:
    build: .
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      CORS_ORIGINS: ${CORS_ORIGINS}
      SERVICE_HOST: ${SERVICE_HOST}
      SERVICE_PORT: ${SERVICE_PORT}
    expose:
      - "${SERVICE_PORT}"
    networks:
      - plataforma_network

networks:
  plataforma_network:
    external: true   # não cria a rede, usa a que já existe no seu servidor
