services:
  social-service:
    build: .
    container_name: social-service
    restart: unless-stopped
    env_file:
      - ../content-service/.env
      - .env
    expose:
      - "${SERVICE_PORT}"
    networks:
      - plataforma_network

networks:
  plataforma_network:
    external: true
