services:
  social-service:
    build: .
    container_name: social-service
    restart: unless-stopped
    env_file:
      - ../content-service/.env
      - .env
    expose:
      - "${SERVICE_PORT}"
    volumes:
      - social_publicacoes_arquivos:/code/arquivos
    networks:
      - plataforma_network

volumes:
  social_publicacoes_arquivos:

networks:
  plataforma_network:
    external: true
